name: icapps_translations_example
description: A project used to demo the Todo Reporter
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^3.0.0+1
  kiwi: ^0.1.0
  shared_preferences: ^0.5.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.1
  built_value_generator: ^6.4.0
  kiwi_generator:
    git:
      url: https://github.com/simolus3/kiwi.git
      ref: 6ead6e68b535bf935df37b29f7d25b283337225e
      path: kiwi_generator
  icapps_translations:
    path: ../

flutter:
  assets:
    - assets/locale/

icapps_translations:
  api_key: 'enter-your-api-key'
  default_language: 'nl'
  languages: ['en', 'nl']