name: icapps_translations
description: Dart tool to generate flutter translations code from the icapps translations tool
version: 3.2.0
homepage: https://github.com/icapps/flutter-icapps-translations

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.0
  locale_gen: ^3.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5
